#pragma once
#include <cstdint>
#include <map>
#include <list>
#include <unordered_map>
#include <vector>
#include <optional>

namespace lob {

enum class Side : uint8_t { Buy, Sell };

struct Order {
    uint64_t id;
    Side side;
    double price;
    uint64_t quantity;   // remaining quantity
    uint64_t seq;        // insertion sequence, used for FIFO at a price level
};

struct Trade {
    uint64_t restingOrderId;
    uint64_t incomingOrderId;
    double price;         // trades execute at the resting order's price
    uint64_t quantity;
    uint64_t seq;
};

// Price-time priority limit order book.
//   - Bids kept highest-price-first, asks kept lowest-price-first.
//   - Within a price level, FIFO (first order in, first matched).
//   - O(log P) add/match where P = number of distinct price levels touched.
//   - O(1) cancel via an id -> location index.
class OrderBook {
public:
    // Adds a limit order. Matches immediately against the opposite side while
    // prices cross; any unfilled remainder rests in the book. Returns the
    // trades generated by this call (empty if nothing crossed).
    std::vector<Trade> addLimitOrder(uint64_t id, Side side, double price, uint64_t quantity);

    // Cancels a resting order by id. Returns false if the id is unknown
    // (already filled or already canceled).
    bool cancelOrder(uint64_t id);

    std::optional<double> bestBid() const;
    std::optional<double> bestAsk() const;
    uint64_t bidDepthAt(double price) const;
    uint64_t askDepthAt(double price) const;

    size_t bidLevels() const { return bids_.size(); }
    size_t askLevels() const { return asks_.size(); }
    size_t openOrders() const { return locations_.size(); }

private:
    struct PriceLevel {
        std::list<Order> orders;
    };

    using BidMap = std::map<double, PriceLevel, std::greater<double>>;
    using AskMap = std::map<double, PriceLevel>;

    struct Location {
        Side side;
        double price;
        std::list<Order>::iterator it;
    };

    BidMap bids_;
    AskMap asks_;
    std::unordered_map<uint64_t, Location> locations_;
    uint64_t nextSeq_ = 0;

    std::vector<Trade> matchBuy(uint64_t id, double price, uint64_t& qty);
    std::vector<Trade> matchSell(uint64_t id, double price, uint64_t& qty);
    void restOrder(uint64_t id, Side side, double price, uint64_t qty);
};

} // namespace lob
