#pragma once
#include <cstdint>
#include <map>
#include <unordered_map>
#include <vector>
#include <optional>

namespace lob::v2 {

enum class Side : uint8_t { Buy, Sell };

struct Trade {
    uint64_t restingOrderId;
    uint64_t incomingOrderId;
    double price;
    uint64_t quantity;
};

// Same matching semantics as v1 (price-time priority, trades at resting
// price), but orders live in a preallocated pool with an intrusive doubly
// linked list per price level instead of one heap-allocated std::list node
// per order. Motivation: v1's p99.9 latency (~2us) was dominated by
// allocator traffic; pooling removes per-order malloc/free entirely from
// the steady-state hot path.
class OrderBook {
public:
    explicit OrderBook(size_t reserveOrders = 1 << 20);

    // Appends trades generated by this order to `out` (caller-owned buffer,
    // reused across calls (avoids allocating a fresh vector per order).
    void addLimitOrder(uint64_t id, Side side, double price, uint64_t quantity,
                       std::vector<Trade>& out);

    bool cancelOrder(uint64_t id);

    std::optional<double> bestBid() const;
    std::optional<double> bestAsk() const;
    size_t openOrders() const { return locations_.size(); }
    size_t bidLevels() const { return bids_.size(); }
    size_t askLevels() const { return asks_.size(); }

private:
    static constexpr uint32_t NIL = 0xFFFFFFFF;

    struct Node {
        uint64_t id;
        uint64_t quantity;
        uint32_t prev;
        uint32_t next;
    };

    struct Level {
        uint32_t head = NIL;
        uint32_t tail = NIL;
    };

    using BidMap = std::map<double, Level, std::greater<double>>;
    using AskMap = std::map<double, Level>;

    struct Location {
        Side side;
        double price;
        uint32_t node;
    };

    std::vector<Node> pool_;
    uint32_t freeHead_ = NIL;

    BidMap bids_;
    AskMap asks_;
    std::unordered_map<uint64_t, Location> locations_;

    uint32_t allocNode(uint64_t id, uint64_t qty);
    void freeNode(uint32_t idx);

    void pushBack(Level& level, uint32_t idx);
    void unlink(Level& level, uint32_t idx);

    template <typename Book>
    void matchAgainst(Book& book, uint64_t id, double limit, uint64_t& qty,
                      bool aggressorIsBuy, std::vector<Trade>& out);

    void restOrder(uint64_t id, Side side, double price, uint64_t qty);
};

} // namespace lob::v2
